theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      latest-legend: "22-03-09-0000"
      latest-ucd: "22-03-09-0000"
      previous-legend: "22-03-08-0035"
      previous-ucd: "22-03-08-0035"
